services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: gamevault_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: gamevault_db
    ports:
      - "5444:5432" # Mapeo modificado para evitar conflictos con instalaciones locales
    volumes:
      - gv_pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:8.0
    ports:
      - "27018:27017" # Puerto alternativo
    volumes:
      - gv_mongodata:/data/db

volumes:
  gv_pgdata:
  gv_mongodata:
