version: '3.8'
services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: gamevault_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: gamevault_db
    ports:
      - "5433:5432" # Por si hubiera instalado PostgreSQL localmente, para evitar conflictos
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
