services:
  app:
    image: mcr.microsoft.com/devcontainers/base:debian-12
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    environment:
      TESTCONTAINERS_HOST_OVERRIDE: host.docker.internal
    depends_on:
      - postgres
      - mongodb
      - redis
      - rabbitmq

  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: gamevault_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: gamevault_db
    ports:
      - "5444:5432" # Mapeo modificado para evitar conflictos con instalaciones locales
    volumes:
      - gv_pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:8.0
    ports:
      - "27018:27017" # Puerto alternativo
    volumes:
      - gv_mongodata:/data/db

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - gv_rabbitmqdata:/var/lib/rabbitmq

volumes:
  gv_pgdata:
  gv_mongodata:
  gv_rabbitmqdata:

