spring:
  application:
    name: gamevault
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        type:
          json_format_mapper: com.aleroig.gamevault.config.Jackson3HibernateMapper